# Generated by Django 3.1.2 on 2020-11-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping',
            field=models.CharField(blank=True, choices=[('Pick Up', 'Pick Up'), ('Delivery', 'Delivery')], max_length=50, null=True),
        ),
    ]
