# Generated by Django 3.1.2 on 2020-11-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201102_0523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='addOn_details',
            new_name='add_details',
        ),
    ]
