# Generated by Django 3.1.2 on 2020-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201027_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, choices=[('Meal 1', 'Meal 1'), ('Meal 2', 'Meal 2'), ('Meal 3', 'Meal 3'), ('Meal 4', 'Meal 4'), ('VEGETARIAN OPTION', 'VEGETARIAN OPTION')], max_length=50, null=True),
        ),
    ]
