# Generated by Django 3.1.2 on 2020-11-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20201115_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Ready For Pick Up', 'Ready For Pick Up')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Meal', 'Meal'), ('Vegetarian', 'Vegetarian'), ('Sauces', 'Sauces')], max_length=50, null=True),
        ),
    ]
