# Generated by Django 3.1.2 on 2020-11-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20201115_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Out For Delivery', 'Out For Delivery'), ('Ready For Pick Up', 'Ready For Pick Up')], default='Created', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, choices=[('Meal 1', 'Meal 1'), ('Meal 2', 'Meal 2'), ('Meal 3', 'Meal 3'), ('Meal 4', 'Meal 4'), ('VEGETARIAN OPTION', 'VEGETARIAN OPTION'), ('Sauce', 'Sauce')], max_length=50, null=True),
        ),
    ]
