# Generated by Django 3.1.2 on 2020-10-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201019_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_ht',
            new_name='price',
        ),
    ]
