# Generated by Django 3.1.2 on 2020-11-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20201030_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='delivery',
        ),
        migrations.AlterField(
            model_name='product',
            name='add_on',
            field=models.BooleanField(default=False),
        ),
    ]
