# Generated by Django 3.1.2 on 2020-10-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20201020_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(choices=[('Meal 1', 'Meal 1'), ('Meal 2', 'Meal 2'), ('Meal 3', 'Meal 3'), ('Meal 4', 'Meal 4'), ('VEGETARIAN OPTION', 'VEGETARIAN OPTION')], max_length=50),
        ),
    ]
