# Generated by Django 3.1.2 on 2020-10-24 13:04

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20201023_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=s3direct.fields.S3DirectField(blank=True, default=0.0),
            preserve_default=False,
        ),
    ]
